import { ThreeDResponseType } from "./enums";
import type { BankDefinition } from "./types";

export const BankCodes = {
  AKBANK: "0046",
  AKBANK_NESTPAY: "9046",
  ALBARAKA_TURK: "0203",
  ALTERNATIF_BANK: "0124",
  ANADOLUBANK: "0135",
  DENIZBANK: "0134",
  FIBABANKA: "0103",
  QNB_FINANSBANK: "0111",
  FINANSBANK_NESTPAY: "9111",
  GARANTI_BBVA: "0062",
  HALKBANK: "0012",
  HSBC: "0123",
  ING_BANK: "0099",
  IS_BANKASI: "0064",
  ODEABANK: "0146",
  TURK_EKONOMI_BANKASI: "0032",
  TURKIYE_FINANS: "0206",
  VAKIFBANK: "0015",
  YAPI_KREDI: "0067",
  SEKERBANK: "0059",
  ZIRAAT_BANKASI: "0010",
  AKTIF_YATIRIM: "0143",
  KUVEYT_TURK: "0205",
  VAKIF_KATILIM: "0210",
  ZIRAAT_KATILIM: "0209",
  PAYNET: "9977",
  PAYNKOLAY: "9978",
  HALKODE: "9979",
  TAMI: "9980",
  VAKIFPAYS: "9981",
  ZIRAATPAY: "9982",
  VEPARA: "9983",
  MOKA: "9984",
  AHLPAY: "9985",
  IQMONEY: "9986",
  PAROLAPARA: "9987",
  PAYBULL: "9988",
  PARAMPOS: "9989",
  QNBPAY: "9990",
  SIPAY: "9991",
  HEPSIPAY: "9992",
  PAYTEN: "9993",
  PAYTR: "9994",
  IPARA: "9995",
  PAYU: "9996",
  IYZICO: "9997",
  CARDPLUS: "9998",
  PARATIKA: "9999",
} as const;

const html3D = ThreeDResponseType.RedirectHTML;
const url3D = ThreeDResponseType.RedirectURL;

const defineBank = (bank: BankDefinition): BankDefinition => bank;

export const bankRegistry: BankDefinition[] = [
  defineBank({
    bank_code: BankCodes.AKBANK,
    bank_name: "Akbank",
    gateway_family: "akbank",
    collective_vpos: false,
    installment_api: false,
    commission_auto_add: false,
    supports_sale: true,
    supports_sale_3d: true,
    supports_cancel: true,
    supports_refund: true,
    requires_storekey: true,
    documented: true,
    three_d_response_type: html3D,
  }),
  defineBank({
    bank_code: BankCodes.AKBANK_NESTPAY,
    bank_name: "Akbank Nestpay",
    gateway_family: "nestpay",
    collective_vpos: false,
    installment_api: false,
    commission_auto_add: false,
    supports_sale: true,
    supports_sale_3d: true,
    supports_cancel: true,
    supports_refund: true,
    requires_storekey: true,
    documented: true,
    three_d_response_type: html3D,
  }),
  defineBank({
    bank_code: BankCodes.ALBARAKA_TURK,
    bank_name: "Albaraka Türk",
    gateway_family: "generic",
    collective_vpos: false,
    installment_api: false,
    commission_auto_add: false,
    supports_sale: true,
    supports_sale_3d: true,
    supports_cancel: true,
    supports_refund: true,
    requires_storekey: true,
    documented: false,
    three_d_response_type: url3D,
  }),
  defineBank({
    bank_code: BankCodes.ALTERNATIF_BANK,
    bank_name: "Alternatif Bank",
    gateway_family: "nestpay",
    collective_vpos: false,
    installment_api: false,
    commission_auto_add: false,
    supports_sale: true,
    supports_sale_3d: true,
    supports_cancel: true,
    supports_refund: true,
    requires_storekey: true,
    documented: true,
    three_d_response_type: html3D,
  }),
  defineBank({
    bank_code: BankCodes.ANADOLUBANK,
    bank_name: "Anadolubank",
    gateway_family: "nestpay",
    collective_vpos: false,
    installment_api: false,
    commission_auto_add: false,
    supports_sale: true,
    supports_sale_3d: true,
    supports_cancel: true,
    supports_refund: true,
    requires_storekey: true,
    documented: true,
    three_d_response_type: html3D,
  }),
  defineBank({
    bank_code: BankCodes.DENIZBANK,
    bank_name: "Denizbank",
    gateway_family: "nestpay",
    collective_vpos: false,
    installment_api: false,
    commission_auto_add: false,
    supports_sale: true,
    supports_sale_3d: true,
    supports_cancel: true,
    supports_refund: true,
    requires_storekey: true,
    documented: true,
    three_d_response_type: html3D,
  }),
  defineBank({
    bank_code: BankCodes.FIBABANKA,
    bank_name: "Fibabanka",
    gateway_family: "generic",
    collective_vpos: false,
    installment_api: false,
    commission_auto_add: false,
    supports_sale: true,
    supports_sale_3d: true,
    supports_cancel: true,
    supports_refund: true,
    requires_storekey: true,
    documented: false,
    three_d_response_type: url3D,
  }),
  defineBank({
    bank_code: BankCodes.QNB_FINANSBANK,
    bank_name: "QNB Finansbank",
    gateway_family: "qnb_finansbank",
    collective_vpos: false,
    installment_api: false,
    commission_auto_add: false,
    supports_sale: true,
    supports_sale_3d: true,
    supports_cancel: true,
    supports_refund: true,
    requires_storekey: true,
    documented: true,
    three_d_response_type: url3D,
  }),
  defineBank({
    bank_code: BankCodes.FINANSBANK_NESTPAY,
    bank_name: "Finansbank Nestpay",
    gateway_family: "nestpay",
    collective_vpos: false,
    installment_api: false,
    commission_auto_add: false,
    supports_sale: true,
    supports_sale_3d: true,
    supports_cancel: true,
    supports_refund: true,
    requires_storekey: true,
    documented: true,
    three_d_response_type: html3D,
  }),
  defineBank({
    bank_code: BankCodes.GARANTI_BBVA,
    bank_name: "Garanti BBVA",
    gateway_family: "garanti",
    collective_vpos: false,
    installment_api: false,
    commission_auto_add: false,
    supports_sale: true,
    supports_sale_3d: true,
    supports_cancel: false,
    supports_refund: false,
    requires_storekey: true,
    documented: true,
    three_d_response_type: url3D,
  }),
  defineBank({
    bank_code: BankCodes.HALKBANK,
    bank_name: "Halkbank",
    gateway_family: "nestpay",
    collective_vpos: false,
    installment_api: false,
    commission_auto_add: false,
    supports_sale: true,
    supports_sale_3d: true,
    supports_cancel: true,
    supports_refund: true,
    requires_storekey: true,
    documented: true,
    three_d_response_type: html3D,
  }),
  defineBank({
    bank_code: BankCodes.HSBC,
    bank_name: "HSBC",
    gateway_family: "generic",
    collective_vpos: false,
    installment_api: false,
    commission_auto_add: false,
    supports_sale: true,
    supports_sale_3d: true,
    supports_cancel: true,
    supports_refund: true,
    requires_storekey: true,
    documented: false,
    three_d_response_type: url3D,
  }),
  defineBank({
    bank_code: BankCodes.ING_BANK,
    bank_name: "ING Bank",
    gateway_family: "nestpay",
    collective_vpos: false,
    installment_api: false,
    commission_auto_add: false,
    supports_sale: true,
    supports_sale_3d: true,
    supports_cancel: true,
    supports_refund: true,
    requires_storekey: true,
    documented: true,
    three_d_response_type: html3D,
  }),
  defineBank({
    bank_code: BankCodes.IS_BANKASI,
    bank_name: "İş Bankası",
    gateway_family: "nestpay",
    collective_vpos: false,
    installment_api: false,
    commission_auto_add: false,
    supports_sale: true,
    supports_sale_3d: true,
    supports_cancel: true,
    supports_refund: true,
    requires_storekey: true,
    documented: true,
    three_d_response_type: html3D,
  }),
  defineBank({
    bank_code: BankCodes.ODEABANK,
    bank_name: "Odeabank",
    gateway_family: "generic",
    collective_vpos: false,
    installment_api: false,
    commission_auto_add: false,
    supports_sale: true,
    supports_sale_3d: true,
    supports_cancel: true,
    supports_refund: true,
    requires_storekey: true,
    documented: false,
    three_d_response_type: url3D,
  }),
  defineBank({
    bank_code: BankCodes.TURK_EKONOMI_BANKASI,
    bank_name: "Türk Ekonomi Bankası",
    gateway_family: "nestpay",
    collective_vpos: false,
    installment_api: false,
    commission_auto_add: false,
    supports_sale: true,
    supports_sale_3d: true,
    supports_cancel: true,
    supports_refund: true,
    requires_storekey: true,
    documented: true,
    three_d_response_type: html3D,
  }),
  defineBank({
    bank_code: BankCodes.TURKIYE_FINANS,
    bank_name: "Türkiye Finans",
    gateway_family: "nestpay",
    collective_vpos: false,
    installment_api: false,
    commission_auto_add: false,
    supports_sale: true,
    supports_sale_3d: true,
    supports_cancel: true,
    supports_refund: true,
    requires_storekey: true,
    documented: true,
    three_d_response_type: html3D,
  }),
  defineBank({
    bank_code: BankCodes.VAKIFBANK,
    bank_name: "Vakıfbank",
    gateway_family: "vakifbank",
    collective_vpos: false,
    installment_api: false,
    commission_auto_add: false,
    supports_sale: true,
    supports_sale_3d: true,
    supports_cancel: true,
    supports_refund: true,
    requires_storekey: false,
    documented: true,
    three_d_response_type: url3D,
  }),
  defineBank({
    bank_code: BankCodes.YAPI_KREDI,
    bank_name: "Yapı Kredi Bankası",
    gateway_family: "yapi_kredi",
    collective_vpos: false,
    installment_api: false,
    commission_auto_add: false,
    supports_sale: true,
    supports_sale_3d: true,
    supports_cancel: false,
    supports_refund: false,
    requires_storekey: true,
    documented: true,
    three_d_response_type: url3D,
  }),
  defineBank({
    bank_code: BankCodes.SEKERBANK,
    bank_name: "Şekerbank",
    gateway_family: "nestpay",
    collective_vpos: false,
    installment_api: false,
    commission_auto_add: false,
    supports_sale: true,
    supports_sale_3d: true,
    supports_cancel: true,
    supports_refund: true,
    requires_storekey: true,
    documented: true,
    three_d_response_type: html3D,
  }),
  defineBank({
    bank_code: BankCodes.ZIRAAT_BANKASI,
    bank_name: "Ziraat Bankası",
    gateway_family: "nestpay",
    collective_vpos: false,
    installment_api: false,
    commission_auto_add: false,
    supports_sale: true,
    supports_sale_3d: true,
    supports_cancel: true,
    supports_refund: true,
    requires_storekey: true,
    documented: true,
    three_d_response_type: html3D,
  }),
  defineBank({
    bank_code: BankCodes.AKTIF_YATIRIM,
    bank_name: "Aktif Yatırım Bankası",
    gateway_family: "generic",
    collective_vpos: false,
    installment_api: false,
    commission_auto_add: false,
    supports_sale: true,
    supports_sale_3d: true,
    supports_cancel: true,
    supports_refund: true,
    requires_storekey: true,
    documented: false,
    three_d_response_type: url3D,
  }),
  defineBank({
    bank_code: BankCodes.KUVEYT_TURK,
    bank_name: "Kuveyt Türk",
    gateway_family: "katilim",
    collective_vpos: false,
    installment_api: false,
    commission_auto_add: false,
    supports_sale: true,
    supports_sale_3d: true,
    supports_cancel: false,
    supports_refund: false,
    requires_storekey: true,
    documented: true,
    three_d_response_type: url3D,
  }),
  defineBank({
    bank_code: BankCodes.VAKIF_KATILIM,
    bank_name: "Vakıf Katılım",
    gateway_family: "katilim",
    collective_vpos: false,
    installment_api: false,
    commission_auto_add: false,
    supports_sale: true,
    supports_sale_3d: true,
    supports_cancel: false,
    supports_refund: false,
    requires_storekey: true,
    documented: true,
    three_d_response_type: url3D,
  }),
  defineBank({
    bank_code: BankCodes.ZIRAAT_KATILIM,
    bank_name: "Ziraat Katılım",
    gateway_family: "generic",
    collective_vpos: false,
    installment_api: false,
    commission_auto_add: false,
    supports_sale: true,
    supports_sale_3d: true,
    supports_cancel: true,
    supports_refund: true,
    requires_storekey: true,
    documented: false,
    three_d_response_type: url3D,
  }),
  defineBank({
    bank_code: BankCodes.PAYNET,
    bank_name: "Paynet",
    gateway_family: "paynet",
    collective_vpos: true,
    installment_api: true,
    commission_auto_add: true,
    supports_sale: true,
    supports_sale_3d: true,
    supports_cancel: true,
    supports_refund: true,
    requires_storekey: false,
    documented: true,
    three_d_response_type: html3D,
  }),
  defineBank({
    bank_code: BankCodes.PAYNKOLAY,
    bank_name: "PayNKolay",
    gateway_family: "paynkolay",
    collective_vpos: true,
    installment_api: true,
    commission_auto_add: true,
    supports_sale: true,
    supports_sale_3d: true,
    supports_cancel: true,
    supports_refund: true,
    requires_storekey: true,
    documented: true,
    three_d_response_type: url3D,
  }),
  defineBank({
    bank_code: BankCodes.HALKODE,
    bank_name: "HalkÖde",
    gateway_family: "ccpayment",
    collective_vpos: true,
    installment_api: true,
    commission_auto_add: true,
    supports_sale: true,
    supports_sale_3d: true,
    supports_cancel: true,
    supports_refund: true,
    requires_storekey: true,
    documented: true,
    three_d_response_type: url3D,
  }),
  defineBank({
    bank_code: BankCodes.TAMI,
    bank_name: "Tami",
    gateway_family: "tami",
    collective_vpos: true,
    installment_api: true,
    commission_auto_add: true,
    supports_sale: true,
    supports_sale_3d: true,
    supports_cancel: true,
    supports_refund: true,
    requires_storekey: true,
    documented: true,
    three_d_response_type: url3D,
  }),
  defineBank({
    bank_code: BankCodes.VAKIFPAYS,
    bank_name: "VakıfPayS",
    gateway_family: "payten",
    collective_vpos: true,
    installment_api: true,
    commission_auto_add: true,
    supports_sale: true,
    supports_sale_3d: true,
    supports_cancel: true,
    supports_refund: true,
    requires_storekey: false,
    documented: true,
    three_d_response_type: url3D,
  }),
  defineBank({
    bank_code: BankCodes.ZIRAATPAY,
    bank_name: "ZiraatPay",
    gateway_family: "payten",
    collective_vpos: true,
    installment_api: true,
    commission_auto_add: true,
    supports_sale: true,
    supports_sale_3d: true,
    supports_cancel: true,
    supports_refund: true,
    requires_storekey: false,
    documented: true,
    three_d_response_type: url3D,
  }),
  defineBank({
    bank_code: BankCodes.VEPARA,
    bank_name: "Vepara",
    gateway_family: "ccpayment",
    collective_vpos: true,
    installment_api: true,
    commission_auto_add: true,
    supports_sale: true,
    supports_sale_3d: true,
    supports_cancel: true,
    supports_refund: true,
    requires_storekey: true,
    documented: true,
    three_d_response_type: url3D,
  }),
  defineBank({
    bank_code: BankCodes.MOKA,
    bank_name: "Moka",
    gateway_family: "moka",
    collective_vpos: true,
    installment_api: true,
    commission_auto_add: true,
    supports_sale: true,
    supports_sale_3d: true,
    supports_cancel: true,
    supports_refund: true,
    requires_storekey: false,
    documented: true,
    three_d_response_type: url3D,
  }),
  defineBank({
    bank_code: BankCodes.AHLPAY,
    bank_name: "Ahlpay",
    gateway_family: "ahlpay",
    collective_vpos: true,
    installment_api: true,
    commission_auto_add: true,
    supports_sale: true,
    supports_sale_3d: true,
    supports_cancel: true,
    supports_refund: true,
    requires_storekey: true,
    documented: true,
    three_d_response_type: url3D,
  }),
  defineBank({
    bank_code: BankCodes.IQMONEY,
    bank_name: "IQmoney",
    gateway_family: "ccpayment",
    collective_vpos: true,
    installment_api: true,
    commission_auto_add: true,
    supports_sale: true,
    supports_sale_3d: true,
    supports_cancel: true,
    supports_refund: true,
    requires_storekey: true,
    documented: true,
    three_d_response_type: url3D,
  }),
  defineBank({
    bank_code: BankCodes.PAROLAPARA,
    bank_name: "Parolapara",
    gateway_family: "ccpayment",
    collective_vpos: true,
    installment_api: true,
    commission_auto_add: true,
    supports_sale: true,
    supports_sale_3d: true,
    supports_cancel: true,
    supports_refund: true,
    requires_storekey: true,
    documented: true,
    three_d_response_type: url3D,
  }),
  defineBank({
    bank_code: BankCodes.PAYBULL,
    bank_name: "PayBull",
    gateway_family: "ccpayment",
    collective_vpos: true,
    installment_api: true,
    commission_auto_add: true,
    supports_sale: true,
    supports_sale_3d: true,
    supports_cancel: true,
    supports_refund: true,
    requires_storekey: true,
    documented: true,
    three_d_response_type: url3D,
  }),
  defineBank({
    bank_code: BankCodes.PARAMPOS,
    bank_name: "ParamPos",
    gateway_family: "parampos",
    collective_vpos: true,
    installment_api: true,
    commission_auto_add: true,
    supports_sale: true,
    supports_sale_3d: true,
    supports_cancel: true,
    supports_refund: true,
    requires_storekey: true,
    documented: true,
    three_d_response_type: url3D,
  }),
  defineBank({
    bank_code: BankCodes.QNBPAY,
    bank_name: "QNBpay",
    gateway_family: "ccpayment",
    collective_vpos: true,
    installment_api: true,
    commission_auto_add: true,
    supports_sale: true,
    supports_sale_3d: true,
    supports_cancel: true,
    supports_refund: true,
    requires_storekey: true,
    documented: true,
    three_d_response_type: url3D,
  }),
  defineBank({
    bank_code: BankCodes.SIPAY,
    bank_name: "Sipay",
    gateway_family: "ccpayment",
    collective_vpos: true,
    installment_api: true,
    commission_auto_add: true,
    supports_sale: true,
    supports_sale_3d: true,
    supports_cancel: true,
    supports_refund: true,
    requires_storekey: true,
    documented: true,
    three_d_response_type: url3D,
  }),
  defineBank({
    bank_code: BankCodes.HEPSIPAY,
    bank_name: "Hepsipay",
    gateway_family: "generic",
    collective_vpos: true,
    installment_api: true,
    commission_auto_add: true,
    supports_sale: true,
    supports_sale_3d: true,
    supports_cancel: true,
    supports_refund: true,
    requires_storekey: false,
    documented: false,
    three_d_response_type: url3D,
  }),
  defineBank({
    bank_code: BankCodes.PAYTEN,
    bank_name: "Payten (MSU)",
    gateway_family: "payten",
    collective_vpos: true,
    installment_api: true,
    commission_auto_add: true,
    supports_sale: true,
    supports_sale_3d: true,
    supports_cancel: true,
    supports_refund: true,
    requires_storekey: false,
    documented: true,
    three_d_response_type: url3D,
  }),
  defineBank({
    bank_code: BankCodes.PAYTR,
    bank_name: "PayTR",
    gateway_family: "generic",
    collective_vpos: true,
    installment_api: true,
    commission_auto_add: false,
    supports_sale: true,
    supports_sale_3d: true,
    supports_cancel: true,
    supports_refund: true,
    requires_storekey: false,
    documented: false,
    three_d_response_type: url3D,
  }),
  defineBank({
    bank_code: BankCodes.IPARA,
    bank_name: "IPara",
    gateway_family: "generic",
    collective_vpos: true,
    installment_api: true,
    commission_auto_add: false,
    supports_sale: true,
    supports_sale_3d: true,
    supports_cancel: true,
    supports_refund: true,
    requires_storekey: false,
    documented: false,
    three_d_response_type: url3D,
  }),
  defineBank({
    bank_code: BankCodes.PAYU,
    bank_name: "PayU",
    gateway_family: "generic",
    collective_vpos: true,
    installment_api: true,
    commission_auto_add: false,
    supports_sale: true,
    supports_sale_3d: true,
    supports_cancel: true,
    supports_refund: true,
    requires_storekey: false,
    documented: false,
    three_d_response_type: url3D,
  }),
  defineBank({
    bank_code: BankCodes.IYZICO,
    bank_name: "Iyzico",
    gateway_family: "iyzico",
    collective_vpos: true,
    installment_api: true,
    commission_auto_add: false,
    supports_sale: true,
    supports_sale_3d: true,
    supports_cancel: true,
    supports_refund: true,
    requires_storekey: false,
    documented: true,
    three_d_response_type: url3D,
  }),
  defineBank({
    bank_code: BankCodes.CARDPLUS,
    bank_name: "Cardplus",
    gateway_family: "nestpay",
    collective_vpos: false,
    installment_api: false,
    commission_auto_add: false,
    supports_sale: true,
    supports_sale_3d: true,
    supports_cancel: true,
    supports_refund: true,
    requires_storekey: true,
    documented: true,
    three_d_response_type: html3D,
  }),
  defineBank({
    bank_code: BankCodes.PARATIKA,
    bank_name: "Paratika",
    gateway_family: "payten",
    collective_vpos: true,
    installment_api: true,
    commission_auto_add: true,
    supports_sale: true,
    supports_sale_3d: true,
    supports_cancel: true,
    supports_refund: true,
    requires_storekey: false,
    documented: true,
    three_d_response_type: url3D,
  }),
];

export const bankMap = new Map<string, BankDefinition>(
  bankRegistry.map((bank) => [bank.bank_code, bank]),
);
